source "https://rubygems.org"

ruby "3.4.8"

gem "jekyll", "~> 4.3"
gem "jekyll-sass-converter", "~> 3.0"

# Plugins used by this site
gem "jekyll-theme-slate"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-redirect-from"

# Stdlib gems extracted from Ruby 3.x
gem "base64"
gem "bigdecimal"
gem "csv"
gem "drb"
gem "mutex_m"

group :jekyll_plugins do
  gem "webrick"
end
