name: tests

on:
    pull_request:
    push:
        branches:
          - main

jobs:
    run:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                    - '8.5'
                minimum_versions: [false]
                coverage: ['none']
                include:
                    - description: 'Minimum version'
                      php: '7.4'
                      minimum_versions: true

        name: PHP ${{ matrix.php }} ${{ matrix.description }}
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
              with:
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}

            - name: Setup PHP
              uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov

            - name: Install dependencies
              run: composer install
              if: matrix.minimum_versions == false

            - name: Install dependencies (lowest versions)
              run: composer update --no-interaction --prefer-lowest
              if: matrix.minimum_versions == true

            - name: Run PHPUnit tests
              run: vendor/bin/phpunit
